### Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

In [20]:
import numpy as np

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [21]:
list_ = [1, 2, 3, 4, 5]

array_list = np.array(object = list_)
print(type(array_list))
print(type(list_))

<class 'numpy.ndarray'>
<class 'list'>


list_ is a Python list and array_list is a NumPy array, then there is a difference in the data type of the two variables.

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [22]:
for i in list_:
    print(type(i))
for j in array_list:
    print(type(j))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.
Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [23]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

print('Data type of array list')
for i in num_array:
    for j in i:
        print(type(j))
print('\nData type of array list')
for i in list_:
    print(type(i))

Data type of array list
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>

Data type of array list
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [32]:
print('shape of array list',num_array.shape)
print('size of array',num_array.size)

shape of array list (2, 3)
size of array 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function. 
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [35]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
